# Update to berry later

enableGlobalCache: true

# httpProxy: 'http://127.0.0.1:8889'

# httpsProxy: 'http://127.0.0.1:8889'

nmMode: classic

nodeLinker: node-modules

progressBarStyle: patrick

# yarnPath: .yarn/releases/yarn-3.2.0.js

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
