enableGlobalCache: true

httpProxy: 'http://127.0.0.1:8889'

httpsProxy: 'http://127.0.0.1:8889'

nmMode: classic

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npm.taobao.org/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-3.1.1.js

nmHoistingLimits: workspaces
