android_binary(
    name = "nawb-app",
    srcs = glob(["app/src/main/java/**/*.java"]),
    manifest = "app/src/main/AndroidManifest.xml",
    manifest_values = {
        applicationId: "com.deskbtm.nawb",
        minSdkVersion: 21,
        compileSdkVersion: 30,
        targetSdkVersion: 28,
    },
    resource_files = glob(["app/src/main/res/**/*"]),
    #    deps = [
    #    ],
)
